name: Workflow_1
on: 
  push:
jobs:
  job_1_for_Instakk_NodeJS:
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout to repo NodeJS
        uses: actions/checkout@v3
      
      - name: Download the Node JS Version
        uses: actions/setup-node@v3
        with:
          node-version: '18'    
      
      - name: Installing npm dependecies
        run: npm ci 

      - name: Installing test
        run: npm test  && echo "test done" 

      - name: run lint
        run: npm run lint 
        
      - name: Builing Project
        run: npm run build

      - name: Deploy 
        run: echo "Deployed "   

      #- name: run listers
      #  uses:  wearerequired/lint-action@v2
      #  with: 
      #    eslint: true
      #    prettier: true      
      




        
        


      