name: downloading_Code

on: [push, workflow_dispatch]
   # branches:
    #  - main  

jobs:
  Checkout_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

  install:
    needs: Checkout_jobs  
    runs-on: ubuntu-latest 
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check Node.js version
        run: node -v

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build and test
        run: |
          npm run build
          npm test

  artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload the Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: my-build
          path: dist

      - name: Verify the files
        run: |
          echo "Files inside dist:"
          ls -R dist
