name: Test Project
on: push  # Trigger when code is pushed
jobs:
  test:   # Job name
    runs-on: ubuntu-latest
    steps:
      - name: Download the code to the repo
        uses: actions/checkout@v4
      - name: Install Node js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Installing dependencies
        run: npm ci
      - name: Testing
        run: npm test
